version: "3.5"
services:
  app:
    image: aquariumbio/aquarium:2.7.2
    command: ["production"]
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      S3_ACCESS_KEY_ID: ${S3_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      S3_REGION: ${S3_REGION}
      TZ: ${TIMEZONE}
    volumes:
      - public:/aquarium/public
      - logs:/aquarium/log
      - shared:/aquarium/shared
      - ./config/instance.yml:/aquarium/config/instance.yml
    networks:
      - aquarium_net
    expose:
      - "3000"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.route_localnet=1

  krill:
    image: aquariumbio/aquarium:2.7.2
    command: ["krill", "production"]
    networks:
      - aquarium_net
    expose:
      - "3500"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TZ: ${TIMEZONE}
    depends_on:
      - app
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.route_localnet=1

  web:
    image: nginx:stable-alpine
    ports:
      - "${APP_PUBLIC_PORT}:80"
    networks:
      - aquarium_net
    depends_on:
      - app
    volumes:
      - public:/aquarium/public
      - logs:/aquarium/log
      - shared:/aquarium/shared

networks:
  aquarium_net:

volumes:
  public:
  logs:
  shared:
